project:
  type: website

website:
  title: "ACM Guides"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/AlishChhetri/ac-acm-installation-guides

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-location: right
    toc-depth: 4
